insert into customer(name, age, active) values ("alice", 50, true)
insert into customer(name, age, active) values ("bob", 20, false)
insert into customer(name, age, active) values ("charlie", 30, true)

insert into product(name, category, price, manufacturer, unit_in_stock, description) value("A", "CategoryA", 1000, "ManufacturerA", 100, "DescriptionA")
insert into product(name, category, price, manufacturer, unit_in_stock, description) value("Macbook", "Potable Computer", 150, "Apple", 1, "IWantIt")
insert into product(name, category, price, manufacturer, unit_in_stock, description) value("B", "CategoryB", 10000, "ManuB", 100, "No comment")
insert into product(name, category, price, manufacturer, unit_in_stock, description) value("C", "etc", 20000, "ManuC", 200, "No comment")
insert into product(name, category, price, manufacturer, unit_in_stock, description) value("D", "etc", 30000, "ManuD", 300, "No comment")
insert into product(name, category, price, manufacturer, unit_in_stock, description) value("E", "etc", 40000, "ManuE", 400, "No comment")
insert into product(name, category, price, manufacturer, unit_in_stock, description) value("Sapp", "nogada", 18, "him_dum", 20000, "ga_bo_get_ser")
insert into product(name, category, price, manufacturer, unit_in_stock, description) value("alice", "CategoryA", 1000, "ManufacturerA", 100, "DescriptionA")
insert into product(name, category, price, manufacturer, unit_in_stock, description) value("bob", "CategoryB", 1000, "ManufacturerB", 100, "DescriptionB")
insert into product(name, category, price, manufacturer, unit_in_stock, description) value("sulma", "read", 1000, "noo", 100, "Description")